version: "3"
services:
  api:
    build: .
    ports:
#      - <port on localhost>:<port on container>
      - 8000:8000
#    env_file:
#      - ./.env
    environment:
      - DATABASE_HOSTNAME=postgres
      - DATABASE_PORT=5432
      - DATABASE_PASSWORD=1111
      - DATABASE_NAME=budgetlesh
      - DATABASE_USERNAME=postgres
      - SECRET_KEY=1we324wqfew5grvsd5tvgrsdw45e2341frewvfwr3421rfre4f4deq4rdrq4rf245g3h6g75unj
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=60
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    depends_on:
      - postgres

  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=1111
      - POSTGRES_DB=budgetlesh
    volumes:
      - postgres-db:/var/lib/postgresql/data

volumes:
  postgres-db: